env:
  - GRADLE_OPTS="-Dorg.gradle.console=plain -Dgradle.publish.key='$GRADLE_PUBLISH_KEY' -Dgradle.publish.secret='$GRADLE_PUBLISH_SECRET'"
language: java
script:
  - ./gradlew -p svg-2-android-vector
  - ./gradlew -p setup-android-sdk publishToMavenLocal # Publish locally to consume in example-android-project
  - ./validate_plugin
#deploy:
#  - provider: script
#    script: ./gradlew -p svg-2-android-vector publishPlugins
#    on:
#      branch: master
tags: true