name: SVG 2 Android Gradle Plugin

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 8 ]

    env:
      GRADLE_OPTS: -Dorg.gradle.console=plain -Dorg.gradle.jvmargs=-XX:MaxMetaspaceSize=512m

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build and Test
      run: |
        ./gradlew -p svg-2-android-vector
        ./gradlew -p svg-2-android-vector publishToMavenLocal # Publish locally to consume in example-android-project
        ./validate_plugin

  deploy:
    if: ${{ contains(github.ref, 'refs/tags/') }}

    needs: [build]

    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: -Dorg.gradle.console=plain -Dorg.gradle.jvmargs=-XX:MaxMetaspaceSize=512m -Dgradle.publish.key='${{ secrets.GRADLE_PUBLISH_KEY }}' -Dgradle.publish.secret='${{ secrets.GRADLE_PUBLISH_SECRET }}'

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Deploy
      run: ./gradlew -p svg-2-android-vector publishPlugins
